---
title: "JSC370 Lab 12"
author: "Tianhui Zhao"
output: 
    html_document:
        toc: TRUE
        toc_float: TRUE
---

This is my JSC370 Lab 12 Website.

```{r, echo=FALSE, warning=FALSE, include=FALSE}
library(tidyverse)
library(plotly)
library(widgetframe)
library(tidytext)
```


```{r, echo=FALSE, warning=FALSE, include=FALSE}
sb_locs <- read_csv("https://raw.githubusercontent.com/JSC370/JSC370-2025/refs/heads/main/data/starbucks/starbucks-locations.csv")
sb_nutr <- read_csv("https://raw.githubusercontent.com/JSC370/JSC370-2025/refs/heads/main/data/starbucks/starbucks-menu-nutrition.csv")

sb_locs <- read_csv("https://raw.githubusercontent.com/JSC370/JSC370-2025/refs/heads/main/data/starbucks/starbucks-locations.csv")

sb_nutr <- read_csv("https://raw.githubusercontent.com/JSC370/JSC370-2025/refs/heads/main/data/starbucks/starbucks-menu-nutrition.csv")

usa_pop <- read_csv("https://raw.githubusercontent.com/JSC370/JSC370-2025/refs/heads/main/data/starbucks/us_state_pop.csv")

usa_states<-read_csv("https://raw.githubusercontent.com/JSC370/JSC370-2025/refs/heads/main/data/starbucks/states.csv")
```


## Showcasing plots {.tabset}

### Figure 1

```{r echo=FALSE}
sb_usa <- sb_locs |> filter(Country == "US")

sb_locs_state <- sb_usa |>
  rename(state='State/Province') |>
  group_by(state) |>
  summarize(n_stores=n())

# need state abbreviations
usa_pop_abbr <- 
  full_join(usa_pop, usa_states,
            by = join_by(state == State)
            ) 
  
sb_locs_state <- full_join(sb_locs_state, usa_pop_abbr, by = join_by(state == Abbreviation))

p1_scatter<- ggplot(sb_locs_state, aes(x=population, y = n_stores, colour = state)) + geom_point(alpha = 0.8) + theme_bw()
ggplotly(p1_scatter)
```

### Figure 2

```{r, echo=FALSE, message=FALSE}
p2 <- ggplot(sb_nutr, aes(x = Calories, fill = Category)) + geom_histogram(alpha = 0.5) + theme_bw()

ggplotly(p2)
```

{-}

